// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srmshbfmongacwhafkly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybXNoYmZtb25nYWN3aGFma2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjU1MTQsImV4cCI6MjA3MTEwMTUxNH0.9mr8XM7DJHUy4WoFSh3gk-yNmowzw1nUFWA-T1jXhLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);